// Code generated by ZelusCtl. DO NOT EDIT.

package models

import "time"

// EpisodesModel 单集详情表
type EpisodesModel struct {
	Id         int64     `gorm:"id"`          // 主键ID
	CreateTime time.Time `gorm:"create_time"` // 创建时间
	UpdateTime time.Time `gorm:"update_time"` // 更新时间
	PodcastId  int64     `gorm:"podcast_id"`  // 单集所属节目id
	Title      string    `gorm:"title"`       // 标题
	Subtitle   string    `gorm:"subtitle"`    // 子标题
	TotalTime  int64     `gorm:"total_time"`  // 时长，单位秒
}
