// Code generated by ZelusCtl. DO NOT EDIT.

package models

// EpisodeCountersModel 单集统计数据
type EpisodeCountersModel struct {
	Id           int64 `gorm:"id"`            // 主键id
	PlayCount    int64 `gorm:"play_count"`    // 单集播放数
	CommentCount int64 `gorm:"comment_count"` // 单集评论数
	BarrageCount int64 `gorm:"barrage_count"` // 单集弹幕数
	LikeCount    int64 `gorm:"like_count"`    // 单集点赞数
}
