// Code generated by ZelusCtl. DO NOT EDIT.

package models

import "time"

// LikeEpisodeUserRelationsModel 描述用户与单集的点赞关系
type LikeEpisodeUserRelationsModel struct {
	Id         int64     `gorm:"id"`          // 唯一id
	EpisodeId  int64     `gorm:"episode_id"`  // 单集id
	UserId     int64     `gorm:"user_id"`     // 用户id
	CreateTime time.Time `gorm:"create_time"` // 创建时间
	UpdateTime time.Time `gorm:"update_time"` // 更新时间
}
