// Code generated by ZelusCtl. DO NOT EDIT.

package models

import "time"

// PodcastsModel 节目详情表
type PodcastsModel struct {
	Id              int64     `gorm:"id"`               // 唯一主键id
	CreateTime      time.Time `gorm:"create_time"`      // 创建时间
	UpdateTime      time.Time `gorm:"update_time"`      // 更新时间
	Name            string    `gorm:"name"`             // 节目名称
	Subtitle        string    `gorm:"subtitle"`         // 节目子标题
	DescriptionGuid string    `gorm:"description_guid"` // 节目描述guid
}
