// Code generated by ZelusCtl. DO NOT EDIT.

package models

import "time"

// SubPodcastUserRelationsModel 用于描述用户与订阅的节目关系
type SubPodcastUserRelationsModel struct {
	Id         int64     `gorm:"id"`          // 主键id
	UserId     int64     `gorm:"user_id"`     // 用户id
	PodcastId  int64     `gorm:"podcast_id"`  // 节目id
	UpdateTime time.Time `gorm:"update_time"` // 更新时间
	CreateTime time.Time `gorm:"create_time"` // 创建时间
}
