// Code generated by ZelusCtl. DO NOT EDIT.

package models

import "time"

// UsersModel 用户信息表
type UsersModel struct {
	Id         int64     `gorm:"id"`          // 用户唯一id
	CreateTime time.Time `gorm:"create_time"` // 创建时间
	UpdateTime time.Time `gorm:"update_time"` // 更新时间
	Nickname   string    `gorm:"nickname"`    // 用户昵称
	Avatar     string    `gorm:"avatar"`      // 头像guid
	Sign       string    `gorm:"sign"`        // 用户签名
}
