// Code generated by ZelusCtl. DO NOT EDIT.

package models

import "time"

// UserBindsModel 描述用户id与绑定手机、wx等关系
type UserBindsModel struct {
	Id         int64     `gorm:"id"`          // 唯一主键id
	UserId     int64     `gorm:"user_id"`     // 唯一用户id
	BindType   int64     `gorm:"bind_type"`   // 绑定类型
	BindCode   string    `gorm:"bind_code"`   // 绑定的值
	CreateTime time.Time `gorm:"create_time"` // 创建时间
	UpdateTime time.Time `gorm:"update_time"` // 更新时间
}
