// Code generated by ZelusCtl. DO NOT EDIT.

package models

// PodcastCountersModel 节目统计数据
type PodcastCountersModel struct {
	Id           int64 `gorm:"id"`            // 节目id
	PlayCount    int64 `gorm:"play_count"`    // 单集播放数量汇总
	CommentCount int64 `gorm:"comment_count"` // 单集评论数量汇总
	BarrageCount int64 `gorm:"barrage_count"` // 单集弹幕数量汇总
	SubCount     int64 `gorm:"sub_count"`     // 订阅数
}
