// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package injector

import (
	"github.com/google/wire"
	"github.com/gozelus/zelus_rest/internal/controllers/v1"
	"github.com/gozelus/zelus_rest/internal/services/v1"
)

// Injectors from wire_zelusCtl.go:

func NewV1ControllersUserController() *v1_controllers.UserController {
	userService := v1_services.NewUserService()
	userController := v1_controllers.NewUserController(userService)
	return userController
}

func NewV1ServicesUserService() *v1_services.UserService {
	userService := v1_services.NewUserService()
	return userService
}

func NewV1ControllersEpisodeController() *v1_controllers.EpisodeController {
	episodeService := v1_services.NewEpisodeService()
	episodeController := v1_controllers.NewEpisodeController(episodeService)
	return episodeController
}

func NewV1ServicesEpisodeService() *v1_services.EpisodeService {
	episodeService := v1_services.NewEpisodeService()
	return episodeService
}

// wire_zelusCtl.go:

// 此 set 为代码生成，请勿改动
// 如果有其他依赖注入需求，应该新建文件而不要改动此文件
var zelusCtlSet = wire.NewSet(v1_controllers.NewUserController, v1_services.NewUserService, v1_controllers.NewEpisodeController, v1_services.NewEpisodeService)
