package tpls

var ModelPackageTpl = `// Code generated by ZelusCtl. DO NOT EDIT.

package {{.PackageName}}`

var ModelDefineTpl = `
// {{.ModelName}} {{.TableComment}}
type {{.ModelName}} struct { {{range .Fields}}
 	{{.Name}} {{.TypeName}} ` + "`gorm:\"{{.DbName}}\"`" + ` // {{.Comment}}` + `{{end}} 
}`
