// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package injector

import (
	"database/sql"

	"github.com/google/wire"
	"github.com/gozelus/zelus_rest/example/internal/controller"
	"github.com/gozelus/zelus_rest/example/internal/repo"
	"github.com/gozelus/zelus_rest/example/internal/router"
	"github.com/gozelus/zelus_rest/example/internal/service"
)

// Injectors from wire.go:

func NewRouter() *router.Router {
	db := newdb()
	userRepo := repo.NewUserRepo(db)
	userService := service.NewUserService(userRepo)
	userController := controller.NewUserController(userService)
	routerRouter := router.NewRouter(userController)
	return routerRouter
}

// wire.go:

var set = wire.NewSet(wire.Bind(new(service.UserRepoInter), new(*repo.UserRepo)), wire.Bind(new(controller.UserServiceInter), new(*service.UserService)), wire.Bind(new(router.UserControllerInter), new(*controller.UserController)), repo.NewUserRepo, service.NewUserService, controller.NewUserController, router.NewRouter, newdb)

func newdb() *sql.DB {
	return nil
}
